# Exploratory Data Analysis

In [1]:
import os

os.chdir("../")
os.getcwd()

'/home/hellsdeur/Documents/ufpa/cbcc/2022.2/simulation/magrela-sim'

In [2]:
from src.eda import Selector

## 2. Data Selection

In [3]:
selector = Selector()

In [4]:
selector.read(directory="data/extracted/open_data_year_one/")
selector.read(directory="data/extracted/open_data_year_two/")
selector.read(directory="data/extracted/open_data_2016-12/")

In [5]:
selector.dfs.keys()

dict_keys(['2015_station_data', '2015_trip_data', '2015_weather_data', '2015_status_data', '2016_station_data', '2016_weather_data', '2016_trip_data', '2016-12_station_data', '2016-12_trip_data'])

### Year One

In [6]:
selector.dfs["2015_weather_data"]

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events
0,10/13/2014,71.0,62.0,54.0,55.0,51.0,46.0,87.0,68.0,46.0,...,29.79,29.65,10.0,10.0,4.0,13.0,4.0,21,0.00,Rain
1,10/14/2014,63.0,59.0,55.0,52.0,51.0,50.0,88.0,78.0,63.0,...,29.75,29.54,10.0,9.0,3.0,10.0,5.0,17,0.11,Rain
2,10/15/2014,62.0,58.0,54.0,53.0,50.0,46.0,87.0,77.0,67.0,...,29.71,29.51,10.0,9.0,3.0,18.0,7.0,25,0.45,Rain
3,10/16/2014,71.0,61.0,52.0,49.0,46.0,42.0,83.0,61.0,36.0,...,29.95,29.81,10.0,10.0,10.0,9.0,4.0,-,0.00,Rain
4,10/17/2014,64.0,60.0,57.0,55.0,51.0,41.0,87.0,72.0,46.0,...,29.78,29.73,10.0,10.0,6.0,8.0,3.0,-,0.14,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,10/9/2015,70.0,62.0,55.0,59.0,55.0,50.0,94.0,77.0,63.0,...,29.94,29.90,10.0,7.0,0.0,9.0,4.0,-,0.01,"Fog , Rain"
362,10/10/2015,72.0,66.0,60.0,62.0,57.0,51.0,88.0,79.0,57.0,...,29.75,29.57,10.0,8.0,3.0,16.0,8.0,29,0.77,Rain
363,10/11/2015,66.0,60.0,54.0,51.0,49.0,46.0,84.0,69.0,50.0,...,30.12,30.00,10.0,10.0,10.0,10.0,5.0,-,0.00,NaN
364,10/12/2015,68.0,61.0,54.0,61.0,53.0,46.0,94.0,76.0,59.0,...,30.10,30.05,10.0,7.0,2.0,12.0,6.0,21,0.34,Rain
365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
selector.dfs["2015_station_data"]

,id,name,terminal,lat,long,dockcount,online
0,1,3rd Ave & Broad St,BT-01,47.618418,-122.350964,18,10/13/2014
1,2,2nd Ave & Vine St,BT-03,47.615829,-122.348564,16,10/13/2014
2,3,6th Ave & Blanchard St,BT-04,47.616094,-122.341102,16,10/13/2014
3,4,2nd Ave & Blanchard St,BT-05,47.613110,-122.344208,14,10/13/2014
4,5,2nd Ave & Pine St,CBD-13,47.610185,-122.339641,18,10/13/2014
5,6,7th Ave & Union St,CBD-03,47.610731,-122.332447,20,10/13/2014
6,7,City Hall / 4th Ave & James St,CBD-07,47.603509,-122.330409,18,10/13/2014
7,8,Pine St & 9th Ave,SLU-16,47.613715,-122.331777,20,10/13/2014
8,9,2nd Ave & Spring St,CBD-06,47.605950,-122.335768,20,10/13/2014
9,10,Summit Ave & E Denny Way,CH-01,47.618633,-122.325249,16,10/13/2014
10,11,E Harrison St & Broadway Ave E,CH-02,47.622063,-122.321251,20,10/13/2014
11,12,Summit Ave E & E Republican St,CH-03,47.623367,-122.325279,16,10/13/2014
12,13,15th Ave E & E Thomas St,CH-05,47.620712,-122.312805,16,10/13/2014
13,14,12th Ave & E Denny Way,CH-06,47.618549,-122.317017,15,10/13/2014
14,15,E Pine St & 16th Ave,CH-07,47.615330,-122.311752,18,10/13/2014
15,16,Cal Anderson Park / 11th Ave & Pine St,CH-08,47.615486,-122.318245,26,10/13/2014
16,17,Harvard Ave & E Pine St,CH-09,47.615517,-122.322083,16,10/13/2014
17,18,Bellevue Ave & E Pine St,CH-12,47.615456,-122.326729,18,10/13/2014
18,19,12th Ave & E Mercer St,CH-15,47.624142,-122.316811,16,10/13/2014
19,20,9th Ave N & Mercer St,DPD-01,47.624298,-122.339617,18,10/13/2014
20,21,Children's Hospital / Sandpoint Way NE & 40th ...,DPD-03,47.663509,-122.284119,24,10/13/2014
21,22,Fred Hutchinson Cancer Research Center / Fairv...,EL-01,47.627643,-122.332576,16,10/13/2014
22,23,E Blaine St & Fairview Ave E,EL-03,47.634831,-122.326634,18,10/13/2014
23,24,Eastlake Ave E & E Allison St,EL-05,47.649090,-122.322983,17,10/13/2014
24,25,Frye Art Museum / Terry Ave & Columbia St,FH-01,47.607281,-122.324783,15,10/13/2014
25,26,Seattle University / E Columbia St & 12th Ave,FH-04,47.609239,-122.316651,20,10/13/2014
26,27,6th Ave S & S King St,ID-04,47.598488,-122.326412,16,10/13/2014
27,28,King Street Station Plaza / 2nd Ave Extension ...,PS-05,47.598994,-122.329684,18,10/13/2014
28,29,Occidental Park / Occidental Ave S & S Washing...,PS-04,47.600757,-122.332946,18,10/13/2014
29,30,REI / Yale Ave N & John St,SLU-01,47.619859,-122.330304,20,10/13/2014
30,31,Dexter Ave N & Aloha St,SLU-02,47.627735,-122.342232,18,10/13/2014
31,32,Republican St & Westlake Ave N,SLU-04,47.623165,-122.338203,18,10/13/2014
32,33,PATH / 9th Ave & Westlake Ave,SLU-07,47.618320,-122.338913,18,10/13/2014
33,34,Westlake Ave & 6th Ave,SLU-15,47.613628,-122.337341,20,10/13/2014
34,35,Lake Union Park / Valley St & Boren Ave N,SLU-17,47.626041,-122.335831,16,10/13/2014
35,36,Dexter Ave & Denny Way,SLU-18,47.618285,-122.342205,20,10/13/2014
36,37,Key Arena / 1st Ave N & Harrison St,SLU-19,47.622277,-122.355230,16,10/13/2014
37,38,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,UD-01,47.666145,-122.301491,18,10/13/2014
38,39,NE 42nd St & University Way NE,UD-02,47.658288,-122.313334,18,10/13/2014
39,40,12th Ave & NE Campus Pkwy,UD-04,47.656395,-122.315620,16,10/13/2014
40,41,NE 47th St & 12th Ave NE,UD-07,47.663143,-122.315086,16,10/13/2014
41,42,UW McCarty Hall / Whitman Ct,UW-01,47.660268,-122.304826,16,10/13/2014
42,43,Burke Museum / E Stevens Way NE & Memorial Way NE,UW-02,47.659756,-122.310402,14,10/13/2014
43,44,15th Ave NE & NE 40th St,UW-04,47.655590,-122.311890,16,10/13/2014
44,45,UW Engineering Library / E Stevens Way NE & Je...,UW-06,47.654613,-122.304863,14,10/13/2014
45,46,UW Intramural Activities Building,UW-07,47.653713,-122.302162,14,10/13/2014
46,47,UW Magnuson Health Sciences Center Rotunda / C...,UW-10,47.650725,-122.311188,14,10/13/2014
47,48,Pier 69 / Alaskan Way & Clay St,WF-01,47.614315,-122.354093,24,10/13/2014
48,49,Seattle Aquarium / Alaskan Way S & Elliott Bay...,WF-04,47.607702,-122.341650,18,10/13/2014
49,50,1st Ave & Marion St,CBD-05,47.604058,-122.335800,20,10/13/2014
50,60,12th Ave & E Yesler Way,CD-01,47.602103,-122.316923,16,5/21/2015
51,62,Terry Ave & Stewart St,SLU-20,47.616260,-122.333815,20,6/12/2015
52,63,Union St & 4th Ave,CBD-04,47.609221,-122.335596,18,7/22/2015
53,65,Mercer St & 9th Ave N,SLU-21,47.624769,-122.339408,20,9/19/2015

In [8]:
selector.dfs["2015_trip_data"]

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Annual Member,Male,1960.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Annual Member,Male,1970.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Annual Member,Female,1988.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Annual Member,Female,1977.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Annual Member,Male,1971.0
...,...,...,...,...,...,...,...,...,...,...,...,...
142841,156796,10/12/2015 20:41,10/12/2015 20:47,SEA00358,377.183,E Pine St & 16th Ave,Summit Ave & E Denny Way,CH-07,CH-01,Annual Member,Male,1990.0
142842,156797,10/12/2015 20:43,10/12/2015 20:48,SEA00399,303.330,Bellevue Ave & E Pine St,Summit Ave E & E Republican St,CH-12,CH-03,Annual Member,Male,1978.0
142843,156798,10/12/2015 21:03,10/12/2015 21:06,SEA00204,165.597,Harvard Ave & E Pine St,E Harrison St & Broadway Ave E,CH-09,CH-02,Annual Member,Male,1989.0
142844,156799,10/12/2015 21:35,10/12/2015 21:41,SEA00073,388.576,Pine St & 9th Ave,3rd Ave & Broad St,SLU-16,BT-01,Short-Term Pass Holder,NaN,NaN
142845,156800,10/12/2015 22:45,10/12/2015 22:51,SEA00033,391.885,NE 42nd St & University Way NE,Eastlake Ave E & E Allison St,UD-02,EL-05,Annual Member,Male,1985.0

In [9]:
selector.dfs["2015_status_data"]

,station_id,bikes_available,docks_available,bikes_blocked,docks_blocked,time
0,1,0,16,2,0,2014-10-15 08:29:47
1,2,4,12,0,0,2014-10-15 08:29:47
2,3,7,8,1,0,2014-10-15 08:29:47
3,4,3,11,0,0,2014-10-15 08:29:47
4,5,7,10,1,0,2014-10-15 08:29:47
...,...,...,...,...,...,...
26061833,50,7,13,0,0,2015-10-12 23:59:28
26061834,60,6,10,0,0,2015-10-12 23:59:28
26061835,62,6,14,0,0,2015-10-12 23:59:28
26061836,63,8,9,1,0,2015-10-12 23:59:28
26061837,65,4,16,0,0,2015-10-12 23:59:28

### Year Two - Part 1

In [10]:
selector.dfs["2016_station_data"]

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
0,BT-01,3rd Ave & Broad St,47.618418,-122.350964,10/13/2014,18,NaN,18,NaN
1,BT-03,2nd Ave & Vine St,47.615829,-122.348564,10/13/2014,16,NaN,16,NaN
2,BT-04,6th Ave & Blanchard St,47.616094,-122.341102,10/13/2014,16,NaN,16,NaN
3,BT-05,2nd Ave & Blanchard St,47.613110,-122.344208,10/13/2014,14,NaN,14,NaN
4,CBD-03,7th Ave & Union St,47.610731,-122.332447,10/13/2014,20,NaN,20,NaN
5,CBD-04,Union St & 4th Ave,47.609221,-122.335596,7/27/2015,18,NaN,18,NaN
6,CBD-05,1st Ave & Marion St,47.604058,-122.335800,10/13/2014,20,NaN,20,NaN
7,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN
8,CBD-07,City Hall / 4th Ave & James St,47.603509,-122.330409,10/13/2014,20,NaN,20,NaN
9,CBD-13,2nd Ave & Pine St,47.610185,-122.339641,10/13/2014,18,NaN,18,NaN
10,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
11,CH-01,Summit Ave & E Denny Way,47.618633,-122.325249,10/13/2014,16,NaN,16,NaN
12,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN
13,CH-03,Summit Ave E & E Republican St,47.623367,-122.325279,10/13/2014,16,NaN,16,NaN
14,CH-05,15th Ave E & E Thomas St,47.620712,-122.312805,10/13/2014,16,NaN,16,NaN
15,CH-06,12th Ave & E Denny Way,47.618549,-122.317017,10/13/2014,16,NaN,16,NaN
16,CH-07,E Pine St & 16th Ave,47.615330,-122.311752,10/13/2014,18,NaN,18,NaN
17,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
18,CH-09,Harvard Ave & E Pine St,47.615517,-122.322083,10/13/2014,16,NaN,16,NaN
19,CH-12,Bellevue Ave & E Pine St,47.615456,-122.326729,10/13/2014,18,NaN,14,NaN
20,CH-15,12th Ave & E Mercer St,47.624142,-122.316811,10/13/2014,16,NaN,16,NaN
21,DPD-01,9th Ave N & Mercer St,47.624298,-122.339617,10/13/2014,18,NaN,18,NaN
22,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
23,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN
24,EL-03,E Blaine St & Fairview Ave E,47.634831,-122.326634,10/13/2014,18,NaN,18,NaN
25,EL-05,Eastlake Ave E & E Allison St,47.649090,-122.322983,10/13/2014,18,NaN,18,NaN
26,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
27,FH-04,Seattle University / E Columbia St & 12th Ave,47.609239,-122.316651,10/13/2014,20,NaN,20,NaN
28,ID-04,6th Ave S & S King St,47.598488,-122.326412,10/13/2014,16,NaN,16,NaN
29,PS-04,Occidental Park / Occidental Ave S & S Washing...,47.600757,-122.332946,10/13/2014,18,NaN,18,NaN
30,PS-05,King Street Station Plaza / 2nd Ave Extension ...,47.598994,-122.329684,10/13/2014,18,NaN,18,NaN
31,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN
32,SLU-02,Dexter Ave N & Aloha St,47.627735,-122.342232,10/13/2014,18,NaN,18,NaN
33,SLU-04,Republican St & Westlake Ave N,47.623165,-122.338203,10/13/2014,18,NaN,18,NaN
34,SLU-07,PATH / 9th Ave & Westlake Ave,47.618320,-122.338913,10/13/2014,18,NaN,18,NaN
35,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN
36,SLU-16,Pine St & 9th Ave,47.613715,-122.331777,10/13/2014,20,NaN,20,NaN
37,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,16,NaN
38,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
39,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN
40,SLU-20,Terry Ave & Stewart St,47.616260,-122.333815,6/12/2015,20,NaN,20,NaN
41,SLU-21,Mercer St & 9th Ave N,47.624769,-122.339408,9/15/2015,20,NaN,20,NaN
42,UD-01,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,47.666145,-122.301491,10/13/2014,18,NaN,18,NaN
43,UD-02,NE 42nd St & University Way NE,47.658288,-122.313334,10/13/2014,18,NaN,18,NaN
44,UD-04,12th Ave & NE Campus Pkwy,47.656395,-122.315620,10/13/2014,16,NaN,16,NaN
45,UD-07,NE 47th St & 12th Ave NE,47.663143,-122.315086,10/13/2014,16,NaN,16,NaN
46,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015
47,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN
48,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN
49,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN
50,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN
51,UW-10,UW Magnuson Health Sciences Center Rotunda / C...,47.650725,-122.311188,10/13/2014,16,NaN,16,NaN
52,WF-01,Pier 69 / Alaskan Way & Clay St,47.614315,-122.354093,10/13/2014,18,NaN,24,NaN
53,WF-04,Seattle Aquarium / Alaskan Way S & Elliott Bay...,47.607702,-122.341650,10/13/2014,18,NaN,18,NaN
54,CH-16,Broadway and E Denny Way,47.618640,-122.320777,3/18/2016,18,NaN,18,NaN
55,SLU-22,Thomas St & 5th Ave N,47.620879,-122.347377,7/3/2016,18,NaN,18,NaN
56,UW-11,NE Pacific St/UW Medical Center,47.649952,-122.306263,10/29/2015,16,NaN,16,NaN
57,WF-03,Pier 66 / Alaskan Way & Bell St,47.611370,-122.348702,8/9/2016,18,NaN,18,NaN

In [11]:
selector.dfs["2016_weather_data"]

,Date,Max_Temperature_F,Mean_Temperature_F,Min_TemperatureF,Max_Dew_Point_F,MeanDew_Point_F,Min_Dewpoint_F,Max_Humidity,Mean_Humidity,Min_Humidity,...,Mean_Sea_Level_Pressure_In,Min_Sea_Level_Pressure_In,Max_Visibility_Miles,Mean_Visibility_Miles,Min_Visibility_Miles,Max_Wind_Speed_MPH,Mean_Wind_Speed_MPH,Max_Gust_Speed_MPH,Precipitation_In,Events
0,10/13/2014,71,62.0,54,55,51,46,87,68,46,...,29.79,29.65,10,10,4,13,4,21,0.00,Rain
1,10/14/2014,63,59.0,55,52,51,50,88,78,63,...,29.75,29.54,10,9,3,10,5,17,0.11,Rain
2,10/15/2014,62,58.0,54,53,50,46,87,77,67,...,29.71,29.51,10,9,3,18,7,25,0.45,Rain
3,10/16/2014,71,61.0,52,49,46,42,83,61,36,...,29.95,29.81,10,10,10,9,4,-,0.00,Rain
4,10/17/2014,64,60.0,57,55,51,41,87,72,46,...,29.78,29.73,10,10,6,8,3,-,0.14,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,8/27/2016,72,66.0,61,57,54,50,81,65,46,...,29.88,29.77,10,10,10,16,9,NaN,0.00,NaN
685,8/28/2016,75,68.0,59,54,52,50,80,65,44,...,30.06,30.01,10,10,10,12,9,NaN,0.00,NaN
686,8/29/2016,81,68.0,55,55,53,50,89,65,39,...,30.02,29.95,10,10,6,9,4,NaN,0.00,NaN
687,8/30/2016,70,64.0,57,55,53,52,83,69,53,...,30.01,29.97,10,10,10,14,9,18,0.00,NaN
688,8/31/2016,71,65.0,59,61,56,52,90,77,63,...,29.97,29.96,10,10,8,14,8,NaN,0.00,Rain

In [12]:
selector.dfs["2016_trip_data"]

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1960.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1970.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1988.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1977.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1971.0
...,...,...,...,...,...,...,...,...,...,...,...,...
236060,255241,8/31/2016 23:34,8/31/2016 23:45,SEA00201,679.532,Harvard Ave & E Pine St,2nd Ave & Spring St,CH-09,CBD-06,Short-Term Pass Holder,NaN,NaN
236061,255242,8/31/2016 23:48,9/1/2016 0:20,SEA00247,1965.418,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
236062,255243,8/31/2016 23:47,9/1/2016 0:20,SEA00300,1951.173,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
236063,255244,8/31/2016 23:49,9/1/2016 0:20,SEA00047,1883.299,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN
236064,255245,8/31/2016 23:49,9/1/2016 0:20,SEA00442,1896.031,Cal Anderson Park / 11th Ave & Pine St,6th Ave S & S King St,CH-08,ID-04,Short-Term Pass Holder,NaN,NaN

### Year Two - Part 2

In [13]:
selector.dfs["2016-12_station_data"]

,station_id,name,lat,long,install_date,install_dockcount,modification_date,current_dockcount,decommission_date
0,CH-06,12th Ave & E Denny Way,47.618549,-122.317017,10/13/2014,16,NaN,16,NaN
1,CH-15,12th Ave & E Mercer St,47.624142,-122.316811,10/13/2014,16,NaN,16,NaN
2,CD-01,12th Ave & E Yesler Way,47.602103,-122.316923,5/22/2015,16,8/9/2016,0,8/9/2016
3,UD-04,12th Ave & NE Campus Pkwy,47.656395,-122.315620,10/13/2014,16,NaN,16,NaN
4,CH-05,15th Ave E & E Thomas St,47.620712,-122.312805,10/13/2014,16,NaN,16,NaN
5,UW-04,15th Ave NE & NE 40th St,47.655590,-122.311890,10/13/2014,18,2/20/2015,16,NaN
6,CBD-05,1st Ave & Marion St,47.604058,-122.335800,10/13/2014,20,NaN,20,NaN
7,BT-05,2nd Ave & Blanchard St,47.613110,-122.344208,10/13/2014,14,NaN,14,NaN
8,CBD-13,2nd Ave & Pine St,47.610185,-122.339641,10/13/2014,18,NaN,18,NaN
9,CBD-06,2nd Ave & Spring St,47.605950,-122.335768,10/13/2014,20,11/9/2015,18,NaN
10,BT-03,2nd Ave & Vine St,47.615829,-122.348564,10/13/2014,16,NaN,16,NaN
11,BT-01,3rd Ave & Broad St,47.618418,-122.350964,10/13/2014,18,NaN,18,NaN
12,BT-04,6th Ave & Blanchard St,47.616094,-122.341102,10/13/2014,16,NaN,16,NaN
13,ID-04,6th Ave S & S King St,47.598488,-122.326412,10/13/2014,16,NaN,16,NaN
14,CBD-03,7th Ave & Union St,47.610731,-122.332447,10/13/2014,20,NaN,20,NaN
15,DPD-01,9th Ave N & Mercer St,47.624298,-122.339617,10/13/2014,18,NaN,18,NaN
16,CH-12,Bellevue Ave & E Pine St,47.615456,-122.326729,10/13/2014,18,NaN,16,NaN
17,CH-16,Broadway and E Denny Way,47.618640,-122.320777,3/18/2016,18,NaN,18,NaN
18,UW-02,Burke Museum / E Stevens Way NE & Memorial Way NE,47.659756,-122.310402,10/13/2014,12,2/20/2015,14,NaN
19,UD-01,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,47.666145,-122.301491,10/13/2014,18,NaN,18,NaN
20,CH-08,Cal Anderson Park / 11th Ave & Pine St,47.615486,-122.318245,10/13/2014,28,2/24/2015,26,NaN
21,DPD-03,Children's Hospital / Sandpoint Way NE & 40th ...,47.663509,-122.284119,10/13/2014,30,3/24/2015,24,NaN
22,CBD-07,City Hall / 4th Ave & James St,47.603509,-122.330409,10/13/2014,20,NaN,20,NaN
23,SLU-18,Dexter Ave & Denny Way,47.618285,-122.342205,10/13/2014,20,11/2/2015,0,7/2/2016
24,SLU-02,Dexter Ave N & Aloha St,47.627735,-122.342232,10/13/2014,18,NaN,18,NaN
25,EL-03,E Blaine St & Fairview Ave E,47.634831,-122.326634,10/13/2014,18,NaN,18,NaN
26,CH-02,E Harrison St & Broadway Ave E,47.622063,-122.321251,10/13/2014,18,2/24/2015,20,NaN
27,CH-07,E Pine St & 16th Ave,47.615330,-122.311752,10/13/2014,18,NaN,18,NaN
28,EL-05,Eastlake Ave E & E Allison St,47.649090,-122.322983,10/13/2014,18,NaN,18,NaN
29,EL-01,Fred Hutchinson Cancer Research Center / Fairv...,47.627643,-122.332576,10/13/2014,12,3/27/2015,16,NaN
30,FH-01,Frye Art Museum / Terry Ave & Columbia St,47.607281,-122.324783,10/13/2014,16,3/18/2016,0,3/18/2016
31,CH-09,Harvard Ave & E Pine St,47.615517,-122.322083,10/13/2014,16,NaN,16,NaN
32,SLU-19,Key Arena / 1st Ave N & Harrison St,47.622277,-122.355230,10/13/2014,12,3/4/2015,16,NaN
33,PS-05,King Street Station Plaza / 2nd Ave Extension ...,47.598994,-122.329684,10/13/2014,18,NaN,18,NaN
34,SLU-17,Lake Union Park / Valley St & Boren Ave N,47.626041,-122.335831,10/13/2014,18,2/23/2015,0,9/16/2016
35,SLU-21,Mercer St & 9th Ave N,47.624769,-122.339408,9/15/2015,20,NaN,20,NaN
36,UD-02,NE 42nd St & University Way NE,47.658288,-122.313334,10/13/2014,18,NaN,18,NaN
37,UD-07,NE 47th St & 12th Ave NE,47.663143,-122.315086,10/13/2014,16,NaN,16,NaN
38,UW-11,NE Pacific St/UW Medical Center,47.649952,-122.306263,10/29/2015,16,NaN,16,NaN
39,PS-04,Occidental Park / Occidental Ave S & S Washing...,47.600757,-122.332946,10/13/2014,18,NaN,18,NaN
40,SLU-07,PATH / 9th Ave & Westlake Ave,47.618320,-122.338913,10/13/2014,18,NaN,18,NaN
41,WF-03,Pier 66 / Alaskan Way & Bell St,47.611370,-122.348702,8/9/2016,18,NaN,18,NaN
42,WF-01,Pier 69 / Alaskan Way & Clay St,47.614315,-122.354093,10/13/2014,18,NaN,24,NaN
43,SLU-16,Pine St & 9th Ave,47.613715,-122.331777,10/13/2014,20,NaN,20,NaN
44,SLU-01,REI / Yale Ave N & John St,47.619859,-122.330304,10/13/2014,18,2/24/2015,20,NaN
45,SLU-04,Republican St & Westlake Ave N,47.623165,-122.338203,10/13/2014,18,NaN,18,NaN
46,WF-04,Seattle Aquarium / Alaskan Way S & Elliott Bay...,47.607702,-122.341650,10/13/2014,18,NaN,18,NaN
47,FH-04,Seattle University / E Columbia St & 12th Ave,47.609239,-122.316651,10/13/2014,20,NaN,20,NaN
48,CH-01,Summit Ave & E Denny Way,47.618633,-122.325249,10/13/2014,16,NaN,16,NaN
49,CH-03,Summit Ave E & E Republican St,47.623367,-122.325279,10/13/2014,16,NaN,16,NaN
50,SLU-20,Terry Ave & Stewart St,47.616260,-122.333815,6/12/2015,20,NaN,20,NaN
51,SLU-22,Thomas St & 5th Ave N,47.620879,-122.347377,7/3/2016,18,NaN,18,NaN
52,CBD-04,Union St & 4th Ave,47.609221,-122.335596,7/27/2015,18,NaN,18,NaN
53,UW-06,UW Engineering Library / E Stevens Way NE & Je...,47.654613,-122.304863,10/13/2014,12,2/20/2015,14,NaN
54,UW-07,UW Intramural Activities Building,47.653713,-122.302162,10/13/2014,20,2/20/2015,14,NaN
55,UW-10,UW Magnuson Health Sciences Center Rotunda / C...,47.650725,-122.311188,10/13/2014,16,9/15/2016,0,9/15/2016
56,UW-01,UW McCarty Hall / Whitman Ct,47.660268,-122.304826,10/13/2014,16,10/29/2015,0,10/29/2015
57,SLU-15,Westlake Ave & 6th Ave,47.613628,-122.337341,10/13/2014,12,3/13/2015,20,NaN
58,SLU-23,Lake Union Park / Westlake Ave & Aloha St,47.627209,-122.339630,9/16/2016,16,NaN,16,NaN
59,UW-12,Husky Stadium U-Link/ Montlake Blvd NE & Walla...,47.649077,-122.304118,9/15/2016,18,NaN,18,NaN

In [14]:
selector.dfs["2016-12_trip_data"]

,trip_id,starttime,stoptime,bikeid,tripduration,from_station_name,to_station_name,from_station_id,to_station_id,usertype,gender,birthyear
0,431,10/13/2014 10:31,10/13/2014 10:48,SEA00298,985.935,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1960.0
1,432,10/13/2014 10:32,10/13/2014 10:48,SEA00195,926.375,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1970.0
2,433,10/13/2014 10:33,10/13/2014 10:48,SEA00486,883.831,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1988.0
3,434,10/13/2014 10:34,10/13/2014 10:48,SEA00333,865.937,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Female,1977.0
4,435,10/13/2014 10:34,10/13/2014 10:49,SEA00202,923.923,2nd Ave & Spring St,Occidental Park / Occidental Ave S & S Washing...,CBD-06,PS-04,Member,Male,1971.0
...,...,...,...,...,...,...,...,...,...,...,...,...
263131,283148,12/31/2016 23:01,12/31/2016 23:37,SEA00220,2139.413,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,Burke-Gilman Trail / NE Blakeley St & 24th Ave NE,UD-01,UD-01,Member,Male,1994.0
263132,283149,12/31/2016 23:41,1/1/2017 0:18,SEA00339,2185.038,Seattle Aquarium / Alaskan Way S & Elliott Bay...,Seattle Aquarium / Alaskan Way S & Elliott Bay...,WF-04,WF-04,Short-Term Pass Holder,NaN,NaN
263133,283150,12/31/2016 23:42,1/1/2017 0:18,SEA00126,2173.435,Seattle Aquarium / Alaskan Way S & Elliott Bay...,Seattle Aquarium / Alaskan Way S & Elliott Bay...,WF-04,WF-04,Short-Term Pass Holder,NaN,NaN
263134,283151,12/31/2016 23:47,1/1/2017 0:18,SEA00014,1850.632,Seattle Aquarium / Alaskan Way S & Elliott Bay...,Seattle Aquarium / Alaskan Way S & Elliott Bay...,WF-04,WF-04,Short-Term Pass Holder,NaN,NaN
263135,283152,12/31/2016 23:47,1/1/2017 0:18,SEA00343,1857.877,Seattle Aquarium / Alaskan Way S & Elliott Bay...,Seattle Aquarium / Alaskan Way S & Elliott Bay...,WF-04,WF-04,Short-Term Pass Holder,NaN,NaN

### Selection decision

Given the heterogeneity of the data through the years, the data used in the current analysis and in the simulation project will only take into account data related to the "Year One" section. Furthermore, data for "Year One" is the most complete of the three sets, containing not only trip and station data, but also status and weather.

In [15]:
data = {
    "trip": selector.dfs["2015_trip_data"],
    "station": selector.dfs["2015_station_data"],
    "status": selector.dfs["2015_status_data"],
    "weather": selector.dfs["2015_weather_data"]
}

In [16]:
selector.serialize(data=data, serial_path="data/selected.pickle")